language: java

sudo: false

jdk:
  - oraclejdk8

before_script: cd apiconnector

addons:
    sonarcloud:
        organization: "openml"

script: mvn clean verify -P sonar -Dsonar.login=$SONAR_LOGIN_TOKEN

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $AUTH
  on:
    branch: master
  local_dir: apiconnector/target/apidocs

name: Minion

after_success: mvn jacoco:report coveralls:report
